modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="chilla55_potions"
version="1.0.0"
displayName="Chilla55's Potions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Chilla55"
description='''
Just some usefull Potions
'''

[[dependencies.chilla55_potions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




